### PR TITLE
Update proto

### PR DESCRIPTION
**Pull request by AlekSi**
See comments at https://github.com/qedus/osmpbf/pull/35

### CODE REVIEW

**Comment by AlekSi** [comment]
@Ich5003 PTAL

**Comment by Ich5003** [comment]
> @Ich5003 PTAL

Thank you, looks good to me, if the Build tip test succeeds.

**Comment by AlekSi** [comment]
I believe that's actions-goveralls's bug: https://github.com/shogo82148/actions-goveralls/issues/214

**Comment by AlekSi** [comment]
Tests pass now.

@jongillham PTAL

**Review by jongillham — APPROVED** [review]
Thanks very much for this. I'm happy for it to be merged.

**Pull request merged**
